services:
  - type: static
    name: cinepass-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
